#+TITLE: A Basic Emacs Configuration for Engineers

This is a basic config file I'm creating to make it easy to start with emacs.
It's actually a little more than just "basic". It should have most of the immediate needs for usage.

* Instructions
1. Ensure you have the latest emacs installed.
2. Install some utilities for pdfs through
   #+begin_src bash
     # Almalinux
     yum install autoconf automake gcc libpng-devel make pkgconfig poppler-devel poppler-glib-devel zlib-devel

     # Ubuntu
     apt install autoconf automake gcc libpng-devel make pkgconfig poppler-devel poppler-glib-devel zlib-devel
   #+end_src
3. Create a directory called "org-roam" in your home.
   #+begin_src bash
     mkdir ~/org-roam
   #+end_src
4. Install python language servers with pip. pyenv setups are possible.
   #+begin_src bash
     pip install 'python-language-server[all]' python-lsp-server debugpy
   #+end_src
5. Clone the contents of this repository into your ~/.emacs.d folder.
6. Fire up emacs 2-3 times to ensure everything is installed properly

* Usage Tips and Tricks
1. Some files may not have extensions but you may still want them to open in a particular mode.
   Add the following line at the beginning of the file for this
   #+begin_src python
     # -*- mode: <modename> -*-
   #+end_src
   The first character(s) can be any appropriate comment character.
   Read [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html][the emacs documentation entry]] on this for more.

* More Packages to add
1. A major mode for csv files.
2. Live plotting capabilities (possibly linked to some data files)? (Should be achievable with gnuplot)
